version: '3'
services:
  web:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./struct/volumes/glpi:/var/www/html
      - ./struct/files/nginx/app.vhost:/etc/nginx/conf.d/default
      - ./struct/files/nginx/dhparam.pem:/etc/ssl/certs/dhparam.pem
      - /etc/letsencrypt/live/glpi.lassarie.com/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - /etc/letsencrypt/live/glpi.lassarie.com/privkey.pem:/etc/ssl/certs/privkey.pem
    depends_on:
      - php
      - db

  php:
    build: ./struct/build/php
    container_name: php
    restart: always
    volumes:
      - ./struct/volumes/glpi:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_DATABASE=glpi
      - MYSQL_USER=glpi
      - MYSQL_PASSWORD=glpi@pass
