version: '3'
services:
  web:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./struct/volumes/${SERVICE}:${DOCUMENT_ROOT}:rw
      - ./struct/files/nginx/app.template:/tmp/default.template:ro
      - ./struct/files/nginx/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
      - /etc/letsencrypt/live/${FQDN}/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/${FQDN}/privkey.pem:/etc/ssl/certs/privkey.pem:ro
    environment:
      - FQDN=${FQDN}
      - DOCUMENT_ROOT=${DOCUMENT_ROOT}
    depends_on:
      - php
      - db
    command: /bin/bash -c "envsubst '$${FQDN} $${DOCUMENT_ROOT}' < /tmp/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  php:
    build: ./struct/build/php
    container_name: php
    restart: always
    volumes:
      - ./struct/volumes/${SERVICE}:${DOCUMENT_ROOT}:ro
    depends_on:
      - db

  db:
    image: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - ./struct/volumes/mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_DATABASE=${SERVICE}
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASS}
